version: "3"

services:
  php:
    build: ./build/php
    restart: unless-stopped
    image: re7-php
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:10.5
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  # utilities

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  npm:
    build: ./build/node
    image: re7-node
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  artisan:
    build: ./build/php
    image: re7-php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint:
      - php
      - /var/www/html/artisan
